version: "3.9"

services:
  misp:
    build:
      context: .
      dockerfile: docker/misp/Dockerfile
      target: dev
    volumes:
      - ./bin:/var/www/html/bin
      - ./config:/var/www/html/config
      - ./libraries:/var/www/html/libraries
      - ./plugins:/var/www/html/plugins
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./tests:/var/www/html/tests
      - ./tools:/var/www/html/tools
      - ./webroot:/var/www/html/webroot
      - ./docker/misp/config/app_local.php:/var/www/html/config/app_local.php:delegated
      - ./docker/misp/logs:/var/www/html/logs:delegated
      - ./tmp:/var/www/html/tmp:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      DEBUG: ${DEBUG:-1}
      ADMIN_ORG: ${ADMIN_ORG:-ORGNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@admin.test}
      ADMIN_INITIAL_PASSWORD: ${ADMIN_INITIAL_PASSWORD:-admin}
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: 1

  webserver:
    volumes:
      - ./webroot:/var/www/html/webroot

  db:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - backend-network