openapi: 3.0.0
info:
  version: 1.0.0
  title: MISP API
servers:
  - url: /
tags:
  - name: Attributes
    description: Attributes in MISP can be network indicators (e.g. IP address), system indicators (e.g. a string in memory) or even bank account details.
    externalDocs:
      url: https://www.circl.lu/doc/misp/GLOSSARY.html#misp-attribute
  - name: Events
    description: MISP events are encapsulations for contextually related information represented as attribute and object.
    externalDocs:
      url: https://www.circl.lu/doc/misp/GLOSSARY.html#misp-event
paths:
  /attributes/add/{eventId}:
    post:
      summary: "Add an attribute"
      operationId: addAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/eventIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/AddAttributeRequest"
      responses:
        "200":
          $ref: "#/components/responses/AttributeResponse"
        "403":
          $ref: "#/components/responses/UnauthorizedApiError"
        default:
          $ref: "#/components/responses/ApiError"

  /attributes/edit/{attributeId}:
    put:
      summary: "Edit an attribute"
      operationId: editAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/attributeIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/EditAttributeRequest"
      responses:
        "200":
          $ref: "#/components/responses/AttributeResponse"
        "403":
          $ref: "#/components/responses/UnauthorizedApiError"
        "404":
          $ref: "#/components/responses/NotFoundApiError"
        default:
          $ref: "#/components/responses/ApiError"

  /attributes/delete/{attributeId}:
    delete:
      summary: "Delete an attribute"
      operationId: deleteAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/attributeIdParameter"
      responses:
        "200":
          $ref: "#/components/responses/DeleteAttributeResponse"
        "403":
          $ref: "#/components/responses/UnauthorizedApiError"
        "404":
          $ref: "#/components/responses/NotFoundApiError"
        default:
          $ref: "#/components/responses/ApiError"

  /attributes:
    get:
      summary: "Get a list of attributes"
      operationId: getAttributes
      tags:
        - Attributes
      responses:
        "200":
          $ref: "#/components/responses/AttributeListResponse"
        "403":
          $ref: "#/components/responses/UnauthorizedApiError"
        default:
          $ref: "#/components/responses/ApiError"

  /attributes/view/{attributeId}:
    get:
      summary: "Get an attribute by ID"
      operationId: viewAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/attributeIdParameter"
      responses:
        "200":
          $ref: "#/components/responses/AttributeResponse"
        "403":
          $ref: "#/components/responses/UnauthorizedApiError"
        default:
          $ref: "#/components/responses/ApiError"

components:
  schemas:
    AttributeResponse:
      type: object
      properties:
        id:
          type: string
          format: int64
          nullable: false
          example: "12345"
        event_id:
          type: string
          format: int64
          nullable: false
          example: "12345"
        object_id:
          type: string
          format: int64
          nullable: false
          example: "12345"
          default: "0"
        object_relation:
          type: string
          maxLength: 255
          nullable: true
          default: null
        category:
          type: string
          maxLength: 255
          nullable: false
          example: "ip-src"
        type:
          type: string
          maxLength: 100
          nullable: false
          example: "network-activity"
        value:
          type: string
          maxLength: 131071
          nullable: false
          example: "127.0.0.1"
        to_ids:
          type: boolean
          nullable: false
          default: true
        uuid:
          type: string
          maxLength: 40
          nullable: false
          example: "c99506a6-1255-4b71-afa5-7b8ba48c3b1b"
        timestamp:
          type: string
          format: int64
          nullable: true
          default: "0"
          example: "1617875568"
        distribution:
          type: string
          format: int32
          nullable: false
          default: "0"
          example: "1"
        sharing_group_id:
          type: string
          format: int64
          nullable: false
          example: "1"
        comment:
          type: string
          maxLength: 65535
          nullable: true
          example: "logged source ip"
        deleted:
          type: boolean
          nullable: false
          default: false
        disable_correlation:
          type: boolean
          nullable: false
          default: false
        first_seen:
          type: string
          format: int64
          nullable: true
        last_seen:
          type: string
          format: int64
          nullable: true

    AttributeListResponse:
      type: array
      items:
        $ref: "#/components/schemas/AttributeResponse"

    DeleteAttributeResponse:
      type: object
      properties:
        message:
          type: string
          example: Attribute deleted.

    ApiError:
      type: object
      required:
        - name
        - message
        - url
      properties:
        name:
          type: string
        message:
          type: string
        url:
          type: string
          example: "/attributes"

    UnauthorizedApiError:
      type: object
      required:
        - name
        - message
        - url
      properties:
        name:
          type: string
          example: "Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header."
        message:
          type: string
          example: "Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header."
        url:
          type: string
          example: "/attributes"

    NotFoundApiError:
      type: object
      required:
        - name
        - message
        - url
      properties:
        name:
          type: string
          example: "Invalid attribute"
        message:
          type: string
          example: "Invalid attribute"
        url:
          type: string
          example: "/attributes/1234"

  parameters:
    eventIdParameter:
      name: eventId
      in: path
      description: Numeric ID of the event linked to this attribute
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1

    attributeIdParameter:
      name: attributeId
      in: path
      description: Numeric ID of the attribute to get
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1

    returnFormatParameter:
      name: returnFormat
      in: query
      description: Return type of the restSearch query.
      required: true
      schema:
        type: string
        enum:
          - json
          - xml
          - download
          - stix

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  requestBodies:
    AddAttributeRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - value
            properties:
              event_id:
                type: string
                format: int64
                nullable: true
                example: "12345"
              object_id:
                type: string
                format: int64
                nullable: true
                example: 12345
                default: "0"
              object_relation:
                type: string
                maxLength: 255
                nullable: true
                default: null
              category:
                type: string
                maxLength: 255
                nullable: true
                example: "ip-src"
              type:
                type: string
                maxLength: 100
                nullable: true
                example: "network-activity"
              value:
                type: string
                maxLength: 131071
                nullable: false
                example: "127.0.0.1"
              to_ids:
                type: boolean
                nullable: true
                default: true
              uuid:
                type: string
                maxLength: 40
                nullable: true
                example: "c99506a6-1255-4b71-afa5-7b8ba48c3b1b"
              timestamp:
                type: string
                format: int64
                nullable: true
                default: "0"
                example: "1617875568"
              distribution:
                type: string
                format: int32
                nullable: true
                default: "0"
                example: 1
              sharing_group_id:
                type: string
                format: int64
                nullable: true
                example: "1"
              comment:
                type: string
                maxLength: 65535
                nullable: true
                example: "logged source ip"
              deleted:
                type: boolean
                nullable: true
                default: false
              disable_correlation:
                type: boolean
                nullable: true
                default: false
              first_seen:
                type: string
                format: int64
                nullable: true
              last_seen:
                type: string
                format: int64
                nullable: true

    EditAttributeRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              event_id:
                type: string
                format: int64
                nullable: true
                example: "12345"
              object_id:
                type: string
                format: int64
                nullable: true
                example: 12345
                default: "0"
              object_relation:
                type: string
                maxLength: 255
                nullable: true
                default: null
              category:
                type: string
                maxLength: 255
                nullable: true
                example: "ip-src"
              type:
                type: string
                maxLength: 100
                nullable: true
                example: "network-activity"
              value:
                type: string
                maxLength: 131071
                nullable: true
                example: "127.0.0.1"
              to_ids:
                type: boolean
                nullable: true
                default: true
              uuid:
                type: string
                maxLength: 40
                nullable: true
                example: "c99506a6-1255-4b71-afa5-7b8ba48c3b1b"
              timestamp:
                type: string
                format: int64
                nullable: true
                default: "0"
                example: 1617875568
              distribution:
                type: string
                format: int32
                nullable: true
                default: "0"
                example: 1
              sharing_group_id:
                type: string
                format: int64
                nullable: true
                example: "1"
              comment:
                type: string
                maxLength: 65535
                nullable: true
                example: "logged source ip"
              deleted:
                type: boolean
                nullable: true
                default: false
              disable_correlation:
                type: boolean
                nullable: true
                default: false
              first_seen:
                type: string
                format: int64
                nullable: true
              last_seen:
                type: string
                format: int64
                nullable: true

  responses:
    AttributeResponse:
      description: "An attribute"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AttributeResponse"

    AttributeListResponse:
      description: "A list of attributes"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AttributeListResponse"

    DeleteAttributeResponse:
      description: "Delete attribute response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeleteAttributeResponse"

    ApiError:
      description: "Unexpected API error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"

    NotFoundApiError:
      description: "The specified resource was not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundApiError"

    UnauthorizedApiError:
      description: "Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedApiError"

security:
  - ApiKeyAuth: []
