# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the 2.4 branch
  push:
    branches: [ add-codeception-api-tests ]
  pull_request:
    branches: [ add-codeception-api-tests ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Checkout coolacid/miso-docker
        uses: actions/checkout@v2
        with:
          repository: coolacid/docker-misp
          path: docker-misp
      - name: Build the stack
        run: docker-compose -f misp-docker/docker-compose.yml up -d
      - name: Test
        run: make test
