# This is a basic workflow to help you get started with Actions

name: Docker API Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the 2.4 branch
  push:
    branches: [add-codeception-api-tests]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "add-codeception-api-tests"
          submodules: "recursive"
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          command: composer install -d app/
      - name: Checkout coolacid/docker-misp
        uses: actions/checkout@v2
        with:
          repository: coolacid/docker-misp
          path: coolacid/docker-misp
      - name: Build the stack
        run: |
          ls -la
          docker-compose -f misp-docker/docker-compose.yml up -d
      - name: Run API tests
        run: |
          cd app
          make test
