# This is a basic workflow to help you get started with Actions

name: Docker API Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the 2.4 branch
  push:
    branches: [add-codeception-api-tests]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "add-codeception-api-tests"
          submodules: "recursive"
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          version: 2
          php_extensions: pcntl
          args: --working-dir=app/
      - name: Checkout coolacid/docker-misp
        uses: actions/checkout@v2
        with:
          repository: coolacid/docker-misp
          path: docker-misp
      - name: Build the stack
        run: |
          ls -la
          docker-compose -f /home/runner/work/MISP/MISP/docker-misp/docker-compose.yml -f /home/runner/work/MISP/MISP/app/Test/docker/docker-compose.tests.yml up -d
      - name: Run API tests
        run: |
          docker ps
          ls -la
          cd app/
          make test
